ALTER TABLE growth_scores ADD COLUMN technical_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE growth_scores ADD COLUMN onpage_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE growth_scores ADD COLUMN local_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE growth_scores ADD COLUMN content_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE growth_scores ADD COLUMN performance_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE growth_scores ADD COLUMN mobile_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE growth_scores ADD COLUMN security_score INTEGER NOT NULL DEFAULT 0;
